# Generated by Django 6.0.5 on 2026-05-18 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conocimiento_contable'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='conocimiento_contable',
            new_name='Empresas',
        ),
    ]
